.gitignore
CHANGELOG.md
LICENSE
README.md
dev/.vscode/launch.json
dev/.vscode/settings.json
dev/.vscode/tasks.json
dev/.vscodeignore
dev/package-lock.json
dev/package.json
dev/src/commands/AbstractDockerCommand.ts
dev/src/commands/AbstractGenerateCommand.ts
dev/src/commands/AbstractGenerateStubCommand.ts
dev/src/commands/ClientCommand.ts
dev/src/commands/GenerateClientCommand.ts
dev/src/commands/GenerateHtmlCommand.ts
dev/src/commands/GenerateServerCommand.ts
dev/src/commands/HtmlDocsCommand.ts
dev/src/commands/ServerCommand.ts
dev/src/constants/Constants.ts
dev/src/constants/Strings.json
dev/src/constants/Translator.ts
dev/src/extension.ts
dev/src/test/extension.test.ts
dev/src/test/index.ts
dev/src/util/Logger.ts
dev/tsconfig.json
dev/tslint.json

PR for https://github.com/eclipse/codewind-openapi-vscode/issues/1

[1] Initial commit of the OpenAPI Tools for VS Code

---

Jenkinsfile

Issue #5: Add Jenkinsfile

---

README.md

Signed-off-by: Sarah Ishida <sishida@us.ibm.com>

Grammatical edits to README.md

---

dev/package.json

[10] Update display name
PR for https://github.com/eclipse/codewind-openapi-vscode/issues/10

[10] Update display name

---

Jenkinsfile

Issue #15: Add latest folder in build result

---

README.md

Step 2 is optional
Signed-off-by: Keith Chong kchong@ca.ibm.com

Update README - step 2 is optional

---

README.md

Link to mattermost
Signed-off-by: Keith Chong kchong@ca.ibm.com

Link to mattermost

---

Jenkinsfile

Issue #25: Add latest folder with build_info.properties in download area

---

dev/src/commands/AbstractGenerateCommand.ts
dev/src/commands/AbstractGenerateStubCommand.ts
dev/src/commands/HtmlDocsCommand.ts

OpenAPI: VSCode: Cannot find folders in the workspace

[29] OpenAPI: VSCode: Cannot find folders in the workspace

---

README.md
dev/package-lock.json
dev/package.json

[39] Fix broken link. Bump up version number to 0.4.0

---

dev/package-lock.json
dev/package.json

[56] Bump up version number for 0.5.0
Fixes #56 

[56] Bump up version number for 0.5.0

---

Jenkinsfile

publish the PR builds output to https://download.eclipse.org/codewind/codewind-openapi-vscode/pr/

Publish pull request build output to download area

---

dev/package-lock.json
dev/package.json

[70] Update dependencies and bump up version number for 0.6.0

---

dev/package-lock.json
dev/package.json
dev/src/commands/AbstractDockerCommand.ts
dev/src/commands/AbstractGenerateStubCommand.ts
dev/src/commands/HtmlDocsCommand.ts
dev/src/commands/ServerCommand.ts
dev/src/constants/Constants.ts

[73] Update to 4.2.2 to pick up node-express-server generator

---

dev/src/commands/AbstractGenerateStubCommand.ts

Fixes https://github.com/eclipse/codewind/issues/1733

[1733] OpenAPI: Make use of Open Liberty Library

---

dev/.vscode/launch.json
dev/.vscode/tasks.json
dev/package-lock.json
dev/package.json
dev/src/test/RunTests.ts
dev/src/test/index.ts
dev/src/test/suites/POMUtilitiesTests.ts
dev/src/util/PomUtilities.ts
dev/tsconfig.json

Fixes https://github.com/eclipse/codewind/issues/2546

[2546] Update test dependencies; Minimist security vulnerability

---

Jenkinsfile

Publish builds to archive site

Issue #2700: Publish to archive site

---

dev/package-lock.json
dev/package.json

Update to version 0.12.0

---

Jenkinsfile

https://github.com/eclipse/codewind/issues/1888

Email notification on build failure for codewind-openapi-vscode

---

Jenkinsfile

Remove unreachable steps within post-failure block.
Original Issue: 
https://github.com/eclipse/codewind/issues/1888

Update Email notification

---

dev/package-lock.json
dev/package.json

To fix: eclipse/codewind#3013
Same fix as last time: 3682733#diff-0363ad7b9057a60819fc51e39d90cc47

update to 0.13.0

---

dev/package-lock.json
dev/package.json

Fixes https://github.com/eclipse/codewind/issues/3174 for VS Code

[OpenAPI] Bump up version numbers for 0.14.0

---

dev/package-lock.json
dev/package.json

Fixes https://github.com/eclipse/codewind/issues/3211

[3211] Bump up version for 0.14.1

---

dev/package-lock.json

Fix security vulnerability
For more details, see #108

Update lodash for Master
